/**
 * Stands in for `$app/env/private` in the Vitest "server" project.
 *
 * `$app/env/private` is generated by `svelte-kit sync` and only resolves inside
 * the Kit build. Without this alias the integration tests could not import the
 * real repository at all, and the alternative — duplicating the queries in the
 * test — would verify a copy rather than the code that ships.
 *
 * It reads the same .env the app does, so the tests run against the same local
 * database, exercising the real drizzle client and real SQL.
 */
import 'dotenv/config';

const url = process.env.DATABASE_URL;
if (!url) {
	throw new Error('DATABASE_URL is not set. Integration tests need the local database.');
}

export const DATABASE_URL: string = url;
